language: python
python:
    - "2.6"
    - "2.7"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/13bcb3f981b557d381b4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
install:
    - pip install -q -e . --use-mirrors
script:
    - python setup.py test
